### ISSUE TITLE
AJAX call doesn't finish

### ISSUE THREAD

**Issue by eddiejr** [fballiano/p4a#15]
I've sync the P4A-3.8.5 version in one of my projects an now the "Loading" notification is working forever.

![p4a loading](https://f.cloud.github.com/assets/2214309/1641855/07e6aa40-5867-11e3-81fd-173f76c50ba8.png)

How can I repair it..?

Best regards,

Eddie

**Comment by fballiano** [comment]
is there a javascript error? is it 3.5 or 3.8?

**Comment by eddiejr** [comment]
Sorry, it's 3.8.5.

I guess is a JavaScript error.

**Comment by fballiano** [comment]
what browser is it?

**Comment by eddiejr** [comment]
The JS log in Mozilla Firefox 25 shows this:

TypeError: $(...).popover is not a function - p4a.js:153

**Comment by fballiano** [comment]
I think i committed something from the bootstrap test :-\

**Comment by eddiejr** [comment]
:-\

**Comment by fballiano** [comment]
can you pull and check now? thx!

**Comment by eddiejr** [comment]
Works just great..!!

Thanks!
