### ISSUE TITLE
P4A 3.8.5 calendar (...) bug

### ISSUE THREAD

**Issue by rosni** [fballiano/p4a#17]
Latest commit P4A 3.8.5 cause calendar (...) datepicker doesn't popup. Tested using chrome and firefox.

**Comment by fballiano** [comment]
i'll check asap, thanks

**Comment by fballiano** [comment]
can you try pulling now and test? it should be working.
thanks and let me know :)

**Comment by rosni** [comment]
yes....its working. thanks.
