### ISSUE TITLE
Some weird error in CKEditor and Chrome

### ISSUE THREAD

**Issue by eddiejr** [fballiano/p4a#18]
Hi,

I recently note that the CKEditor 4.2.2 it's failing when is used with Chrome

![error ckeditor 4 2 2 revision f98db6d8](https://f.cloud.github.com/assets/2214309/1707905/48f54d56-6105-11e3-8535-a44ce2ed026a.png)

But if you press the browser's "back" button, the widget works.

![ckeditor working after back button](https://f.cloud.github.com/assets/2214309/1707933/9a5c06da-6105-11e3-91c3-3e72f21e8cc4.png)

But some widgets in the mask do an OnChange event to refresh the fields and the CKEditor dissapears again...

Eddie

**Comment by fballiano** [comment]
did you already try to pull the new version with ckeditor 4.3?

**Comment by eddiejr** [comment]
I've been fetch the upstream (your) repository, and the CKEditor included is 4.2.2; just the reference of 4.3 is in CHANGELOG.

![p4a git message log](https://f.cloud.github.com/assets/2214309/1710756/610e9fca-613a-11e3-9042-584de36b3bd5.png)

![p4a changelog](https://f.cloud.github.com/assets/2214309/1710757/656cfddc-613a-11e3-927a-cfdf291bdf78.png)

Eddie

**Comment by fballiano** [comment]
pushed now, sorry, can you give it a try? thanks!

**Comment by eddiejr** [comment]
Thanks Fabrizio, it's working just fine..!! :D

**Comment by eddiejr** [comment]
Oops..., I spoke too soon...., the same error with CKEditor 4.3.1. I'll upload a demo to replicate the situation.

**Comment by eddiejr** [comment]
Fabrizio,

Check the demo: http://demo.riprogrett.net/ using the credentials that I sent you last week. Go the "Editores de datos"'s button and select some different continent to replicate the issue.

Thanks.

Eddie

**Comment by fballiano** [comment]
ok it seems that ckeditor >4.2 doesn't need to be destroyed/recreated, actually it's better this way.
can you pull and test? it working for me now.
thank you!

**Comment by eddiejr** [comment]
Ok, it's perfectly working Fabrizio, i've uploaded the change to my webserver and the demo works now.

Thank you for the all your time invested.

Eddie

**Comment by fballiano** [comment]
glad it works again, it was quite easy but at the beginning i thought it could be a great trouble :)
