### ISSUE TITLE
More AJAX

### ISSUE THREAD

**Issue by tassoman** [fballiano/p4a#19]
What can you say about triggering AJAX events on P4A? (like table reloading, data editing, select filling)

Manual page is still missing: https://github.com/fballiano/p4a/wiki/How-P4A-manages-AJAX

**Comment by fballiano** [comment]
- select filling is usually done with autocomplete on p4a_field, you should check it out but it's quite independent from ajax events
- if you don't disable ajax via P4A_AJAX_ENABLED constant everything is done via ajax and the whole body of the HTML is replaced after every call (you spare http connections and cache checks)
- you can anyway implement an event with your own interceptor function (like a click on a button) via the usual syntax but adding an ajax action with "addAjaxAction", in the interceptor function you've to decide what widget you want to redesign with eg: $this->buttons->redesign()

really i rough explanation

**Comment by tassoman** [comment]
After reading the forums I've managed to build a field with addAjaxAction('onClick') method and implement('onClick', $this, 'myMaskMethod') then implementing the Mask object's method I've managed to call redesign() method on entire the fieldset after the modifications triggered by field's onClick. Thank you for clarification. :+1:
