### ISSUE TITLE
Composer PHP as autoloader, feature request

### ISSUE THREAD

**Issue by tassoman** [fballiano/p4a#21]
Would be interesting having [Composer PHP](http://getcomposer.org) as installer and 3rd parties libraries management? Using it, you could manage lazy autoloading of classes during development.

The point would be lifting the developer from instancing of object and concentrate him only on objects configuration and business logic.

I feel P4A extremely RAD and fast also not being well MVC but I felt losing time taking care of object creation. (Also IDE integration isn't well coupled, i mean PHPStorm 7.1)

**Comment by fballiano** [comment]
in p4a4 it's going to be like this :)
we'll have a skeleton app and composer will manage the rest ;)
