### ISSUE TITLE
NOTICE "Non-static" on startup 

### ISSUE THREAD

**Issue by zukunft** [fballiano/p4a#27]
With php 5.4.4-14 I got the notice "Non-Static method Net_UserAgent_Detect::detect() should not be called ..." when starting an p4a application. I could remove this message with changing the line 105 in  p4a / p4a / libraries / pear_net_useragent_detect.php to

public static function detect($in_userAgent = null, $in_detect = null)

So I would suggest add static to the function "detect".

**Comment by fballiano** [comment]
Hi!
the library is not managed by us so we shouldn't change its code :(
but you should remove the notice warning in production :)
