### ISSUE TITLE
Modeldriven development for P4A - suggestion

### ISSUE THREAD

**Issue by lollisoft** [fballiano/p4a#32]
Hi,

I have propably posted on the wrong forum. Please see here: http://sourceforge.net/p/p4a/discussion/340766/thread/a0d684a2/

**Comment by fballiano** [comment]
I answered there, thank you very much!

**Comment by lollisoft** [comment]
Copy from sf:

Hi,

I just have created a GIT repository for the template. It is a starting point with my latest version. I like to move / split out this template into it's own repository - eg. GIT.

Here it is: https://github.com/lollisoft/PHP4ApplicationsCompilation

Please give it a try to use my application and generate code with that template my selecting the generate.xsl file in my second dialog (the first will popup only once to chose an output folder).

I think I add some howto and requirements in the next days.

Regards, Lothar

**Comment by fballiano** [comment]
yeah great, looking forward to see some code too :)

**Comment by lollisoft** [comment]
This is all the code. You'll need my software to spit out the xml that is fed into the xslt template.
I thought not to put a sample project to this repo, because this will simply be a reference application
the generator should produce. My software contains more explanations on how to use these templates.
