### ISSUE TITLE
Contribs

### ISSUE THREAD

**Issue by dcarreroc** [fballiano/p4a#9]
Hello Fabrizio
I just upload my contribs to github
- OptionGroup:
  https://github.com/dcarreroc/P4AOptionGroup
- PDFEmbed:
  https://github.com/dcarreroc/p4apdfembed

Greetings

**Comment by fballiano** [comment]
wiki updated

**Comment by fballiano** [comment]
ps: thank you!

**Comment by dcarreroc** [comment]
;)
